export const GET_HOTELS_SUCCESS="GET_HOTELS_SUCCESS"
export const GET_HOTELS_REQUEST="GET_HOTELS_REQUEST"
export const GET_HOTELS_FAILURE="GET_HOTELS_FAILURE"
export const GET_TOTAL_PAGES="GET_TOTAL_PAGES"
