export const GET_HOTELS_SUCCESS="GET_HOTELS_SUCCESS"
export const GET_HOTELS_REQUEST="GET_HOTELS_REQUEST"
export const GET_HOTELS_FAILURE="GET_HOTELS_FAILURE"


export const POST_SIGNUP_DATA = "POST_SIGNUP_DATA"
export const GET_SIGNUP_DATA = "GET_SIGNUP_DATA"